export type SQLTypes =
      "TINYINT"
    | "BOOLEAN"
    | "SMALLINT"
    | "MEDIUMINT"
    | "INT"
    | "INTEGER"
    | "BIGINT"
    | "DECIMAL"
    | "DEC, NUMERIC, FIXED"
    | "FLOAT"
    | "DOUBLE"
    | "DOUBLE PRECISION"
    | "REAL "
    | "BIT"
    | "CHAR"
    | "VARCHAR"
    | "BINARY"
    | "CHAR BYTE"
    | "VARBINARY"
    | "TINYBLOB"
    | "BLOB"
    | "MEDIUMBLOB"
    | "LONGBLOB"
    | "TINYTEXT"
    | "TEXT"
    | "MEDIUMTEXT"
    | "LONGTEXT"
    | "JSON "
    | "ENUM"
    | "SET "
    | "Set"
    | "ROW"
    | "DATE"
    | "TIME"
    | "DATETIME"
    | "TIMESTAMP"
    | "YEAR "
    | "AUTO_INCREMENT"
    | "JSON";